### ISSUE TITLE
Diagraph highlighting ignores newlines

### ISSUE THREAD

**Issue by Vyxal-Bot-old** [Vyxal/Vylight#1]
If you have a diagraph character followed by a newline, the first character on the next line gets highlighted as part of the diagraph. <a href="https://lyxal.pythonanywhere.com?flags=&code=%C3%9E%0AT&inputs=&header=&footer=" rel="nofollow noopener noreferrer">Try it Online!</a>

(created by Aaron Miller [here](https://chat.stackexchange.com/transcript/message/58735797))

**Comment by chunkybanana** [comment]
Fixed.
