### ISSUE TITLE
Constants and compression make highlighting no

### ISSUE THREAD

**Issue by Vyxal-Bot-old** [Vyxal/Vylight#2]
Unlike any other diagraph characters or structure delimiters, a `k` followed by a `«` or `»` character keeps the normal highlighting of the delimiter instead of giving it the highlighting of the constant diagraph. <a href="https://lyxal.pythonanywhere.com?flags=&code=k%C2%AB&inputs=&header=&footer=" rel="nofollow noopener noreferrer">Try it Online!</a>

(created by Aaron Miller [here](https://chat.stackexchange.com/transcript/message/58735840))

**Comment by chunkybanana** [comment]
Fixed.
