### ISSUE TITLE
Multiline strings aren't highlighted properly

### ISSUE THREAD

**Issue by Vyxal-Bot-old** [Vyxal/Vylight#3]
E.g https://vyxal.pythonanywhere.com/#WyIiLCIiLCJgTGluZSAxXG5MaW5lIDJcbkxpbmUgM2AiLCIiLCIiXQ==

(created by lyxal [here](https://chat.stackexchange.com/transcript/message/59730311))

**Comment by chunkybanana** [comment]
Fixed
