### ISSUE TITLE
Comment highlighting never stops

### ISSUE THREAD

**Issue by AMiller42** [Vyxal/Vylight#4]
Once Vylight starts highlighting a comment, the comment highlighting never stops, even for newlines, and the rest of the program is highlighted as a comment.

Example: [Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCIjXG5hYWFhYWFhYWFhYWFhYWFhYWFhYVxuYmJiYmJiYmJiYmJiYmJiYmJiYmJcbmNjY2NjY2NjY2NjY2NjY2NjY2NjXG5kZGRkZGRkZGRkZGRkZGRkZGRkZFxuZWVlZWVlZWVlZWVlZWVlZWVlZWVcbmZmZmZmZmZmZmZmZmZmZmZmZmZmXG5nZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ1xuaGhoaGhoaGhoaGhoaGhoaGhoaGhcbmlpaWlpaWlpaWlpaWlpaWlpaWlpXG5qampqampqampqampqampqampqalxua2tra2tra2tra2tra2tra2tra2tcbmxsbGxsbGxsbGxsbGxsbGxsbGxsXG5tbW1tbW1tbW1tbW1tbW1tbW1tbVxubm5ubm5ubm5ubm5ubm5ubm5ubm5cbm9vb29vb29vb29vb29vb29vb29vXG5wcHBwcHBwcHBwcHBwcHBwcHBwcFxucXFxcXFxcXFxcXFxcXFxcXFxcXFcbnJycnJycnJycnJycnJycnJycnJyXG5zc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc1xudHR0dHR0dHR0dHR0dHR0dHR0dHRcbnV1dXV1dXV1dXV1dXV1dXV1dXV1XG52dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dlxud3d3d3d3d3d3d3d3d3d3d3d3d3dcbnh4eHh4eHh4eHh4eHh4eHh4eHh4XG55eXl5eXl5eXl5eXl5eXl5eXl5eVxuenp6enp6enp6enp6enp6enp6enoiLCIiLCIiXQ==)

**Comment by zoomlogo** [comment]
The program is just a comment lol

**Comment by chunkybanana** [comment]
Fixed.
