### ISSUE TITLE
`@` is still yellow, even though it's no longer function declaration

### ISSUE THREAD

**Issue by nayakrujul** [Vyxal/Vylight#7]
[`@` was changed from function declaration to vectorised length](https://github.com/Vyxal/Vyxal/pull/1690) in 2.20.0, but it's [still highlighted as function declaration](https://vyxal.pythonanywhere.com/#WyIiLCIiLCJAIiwiIiwiIl0=) because [Vylight hasn't been changed](https://github.com/Vyxal/Vylight/blob/gh-pages/mode-vyxal.js#L193). Instead, `¨@` should now be yellow, and `@` shouldn't have highlighting.

**Comment by PlaceReporter99** [comment]
Add the `outdated-highlighting` and `syntax-changes` tags.
